#                ╔═════════════════════════════════════════════════════════╗
#                ║                          GlazeWM                        ║
#                ╚═════════════════════════════════════════════════════════╝
#                ╭─────────────────────────────────────────────────────────╮
#                │                        General                          │
#                ╰─────────────────────────────────────────────────────────╯
general:
  startup_commands:
    ["shell-exec autohotkey C:\\Users\\lli\\.glzr\\ahk\\glzr.ahk"]
  shutdown_commands: []
  config_reload_commands: []
  focus_follows_cursor: true
  toggle_workspace_on_refocus: false
  hide_method: "cloak"
  show_all_in_taskbar: true
  cursor_jump:
    enabled: true
    trigger: "window_focus"
#                ╭─────────────────────────────────────────────────────────╮
#                │                         Gaps                            │
#                ╰─────────────────────────────────────────────────────────╯
gaps:
  scale_with_dpi: true
  inner_gap: "2px"
  outer_gap:
    top: "2px"
    right: "2px"
    bottom: "2px"
    left: "2px"
  single_window_outer_gap:
    top: "2px"
    right: "2px"
    bottom: "2px"
    left: "2px"
#                ╭─────────────────────────────────────────────────────────╮
#                │                    Window Effects                       │
#                ╰─────────────────────────────────────────────────────────╯
window_effects:
  focused_window:
    border:
      enabled: true
      color: "#181616"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "square"
    transparency:
      enabled: false
      opacity: "95%"

  other_windows:
    border:
      enabled: true
      color: "#1b1b1b"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: "square"
    transparency:
      enabled: false
      opacity: "0%"
#                ╭─────────────────────────────────────────────────────────╮
#                │                    Window Behavior                      │
#                ╰─────────────────────────────────────────────────────────╯
window_behavior:
  initial_state: "tiling"
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: false
      shown_on_top: false
#                ╭─────────────────────────────────────────────────────────╮
#                │                        Workspaces                       │
#                ╰─────────────────────────────────────────────────────────╯
workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"
#                ╭─────────────────────────────────────────────────────────╮
#                │                        Rules                            │
#                ╰─────────────────────────────────────────────────────────╯
window_rules:
  # Ignore Rules: ================================================================================
  - commands: ["ignore"]
    match:
      - window_process: { equals: "zebar" }
      - window_title: { regex: "[Pp]icture.in.[Pp]icture" }
        window_class: { regex: "Chrome_WidgetWin_1|MozillaDialogClass" }
      - window_process: { equals: "PowerToys" }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: "PowerToys" }
        window_title: { regex: ".*? - Peek" }
      - window_process: { equals: "Lively" }
        window_class: { regex: "HwndWrapper" }
      - window_process: { equals: "EXCEL" }
        window_class: { not_regex: "XLMAIN" }
      - window_process: { equals: "WINWORD" }
        window_class: { not_regex: "OpusApp" }
      - window_process: { equals: "POWERPNT" }
        window_class: { not_regex: "PPTFrameClass" }
      - window_process: { regex: "SnippingTool" }

  # Floating Rules: ==============================================================================
  - commands: ["set-floating"]
    match:
      - window_process: { regex: "qView|GlassWire|mpv|crow|Taskmgr|obs" }
      - window_process: { regex: "explorer|ChatGPT|SnippingTool" }
      - window_process: { equals: "VirtualBox|VirtualBoxVM" }
      - window_title: { regex: "Window Spy" }
      - window_title: { equals: "Calculator" }
      - window_title: { equals: "Library" }
      - window_title: { equals: "Settings" }

  # Workspaces Rules: ============================================================================
  #  ╭──────────────────────────────────────────────────────────────────────────╮
  #  │ Workspace 1                                                              │
  #  ╰──────────────────────────────────────────────────────────────────────────╯
  - commands: ["move --workspace 1", "focus --workspace 1"]
    match:
      - window_process: { equals: "zed" }
  #  ╭──────────────────────────────────────────────────────────────────────────╮
  #  │ Workspace 2                                                              │
  #  ╰──────────────────────────────────────────────────────────────────────────╯
  - commands: ["move --workspace 2", "focus --workspace 2"]
    match:
      - window_process: { equals: "WindowsTerminal" }
      - window_process: { equals: "explorer" }
      - window_process: { equals: "FreeTube" }
      - window_process: { equals: "qView" }
      - window_process: { equals: "mpv" }
  #  ╭──────────────────────────────────────────────────────────────────────────╮
  #  │ Workspace 3                                                              │
  #  ╰──────────────────────────────────────────────────────────────────────────╯
  - commands: ["move --workspace 3", "focus --workspace 3"]
    match:
      - window_process: { equals: "librewolf" }
      - window_process: { equals: "firefox" }
      - window_process: { equals: "chrome" }
      - window_process: { equals: "zen" }
  #  ╭──────────────────────────────────────────────────────────────────────────╮
  #  │ Workspace 4                                                              │
  #  ╰──────────────────────────────────────────────────────────────────────────╯
  - commands: ["move --workspace 4", "focus --workspace 4"]
    match:
      - window_process: { regex: "gimp" }
      - window_process: { regex: "shotcut" }
      - window_process: { regex: "obs" }
  #  ╭──────────────────────────────────────────────────────────────────────────╮
  #  │ Workspace 5                                                              │
  #  ╰──────────────────────────────────────────────────────────────────────────╯
  - commands: ["move --workspace 5", "focus --workspace 5"]
    match:
      - window_process: { regex: "thunderbird" }
  #  ╭──────────────────────────────────────────────────────────────────────────╮
  #  │ Workspace 6                                                              │
  #  ╰──────────────────────────────────────────────────────────────────────────╯
  - commands: ["move --workspace 6", "focus --workspace 6"]
    match:
      - window_process: { equals: "spotify" }
  # Fullscreen Rules: ============================================================================
  - commands: ["toggle-fullscreen"]
    match:
      - window_process: { equals: "mpv" }
      - window_process: { equals: "qView" }
  # Border Rules: ================================================================================
  - commands: ["adjust-borders --top 6px"]
    match:
      - window_process: { equals: "qutebrowser" }
#                ╭─────────────────────────────────────────────────────────╮
#                │                    binding_modes                        │
#                ╰─────────────────────────────────────────────────────────╯
binding_modes:
  # Resize: =======================================================================================
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      - commands: ["wm-disable-binding-mode --name resize"]
        bindings: ["escape", "enter"]

  # Pause: =======================================================================================
  - name: "pause"
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+control+p"]
#                ╭─────────────────────────────────────────────────────────╮
#                │                      keybindings                        │
#                ╰─────────────────────────────────────────────────────────╯
keybindings:
  # Focus: =======================================================================================
  - commands: ["focus --direction left"]
    bindings: ["alt+h", "alt+left"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l", "alt+right"]
  - commands: ["focus --direction up"]
    bindings: ["alt+k", "alt+up"]
  - commands: ["focus --direction down"]
    bindings: ["alt+j", "alt+down"]

  # Move: ========================================================================================
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left", "alt+s"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]

  # Resize: ======================================================================================
  - commands: ["resize --width -2%"]
    bindings: ["alt+control+h"]
  - commands: ["resize --width +2%"]
    bindings: ["alt+control+l"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+control+j"]
  - commands: ["resize --height -2%"]
    bindings: ["alt+control+k"]

  # mode: ========================================================================================
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+r"]

  # Pause : ======================================================================================
  - commands: ["wm-toggle-pause"]
    bindings: ["alt+control+p"]

  # direction: ===================================================================================
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]

  # Cycle: =======================================================================================
  - commands: ["wm-cycle-focus"]
    bindings: ["alt+space"]

  # Floating: ====================================================================================
  - commands: ["toggle-floating --centered"]
    bindings: ["alt+shift+space"]

  # Tiling: ======================================================================================
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]

  # fullscreen: ==================================================================================
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+f"]

  # Minimize: ====================================================================================
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]

  # Close: =======================================================================================
  - commands: ["close"]
    bindings: ["alt+q"]

  # Kill: ========================================================================================
  - commands: ["wm-exit"]
    bindings: ["alt+control+q"]

  # Reload: ======================================================================================
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]

  # Redraw: ======================================================================================
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]

  # Terminal: ====================================================================================
  - commands: ["shell-exec alacritty"]
    bindings: ["alt+enter"]
  - commands: ["shell-exec wt"]
    bindings: ["alt+shift+enter"]

  # Apps: ========================================================================================
  - commands: ["shell-exec qutebrowser"]
    bindings: ["alt+w"]
  - commands: ["shell-exec msedge"]
    bindings: ["alt+i"]
  - commands: ["shell-exec thunderbird"]
    bindings: ["alt+e"]
  - commands: ["shell-exec elvish -c zed"]
    bindings: ["alt+z"]
  - commands: ["shell-exec wt C:\\Program Files\\Git\\bin\\bash.exe -c yazi"]
    bindings: ["alt+n"]
  - commands:
      [
        "shell-exec C:\\Users\\lli\\scoop\\apps\\freetube\\current\\Freetube.exe",
      ]
    bindings: ["alt+y"]
  - commands: ["shell-exec neovide"]
    bindings: ["alt+shift+v"]
  - commands: ["shell-exec explorer"]
    bindings: ["alt+shift+n"]
  - commands: ["shell-exec trash empty --all"]
    bindings: ["alt+shift+t"]

  # next/previous: ===============================================================================
  - commands: ["focus --next-active-workspace"]
    bindings: ["alt+shift+>"]
  - commands: ["focus --prev-active-workspace"]
    bindings: ["alt+shift+<"]

  # last: ========================================================================================
  - commands: ["focus --recent-workspace"]
    bindings: ["alt+d"]

  # workspace: ===================================================================================
  - commands: ["focus --workspace 1"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace 2"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace 3"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace 4"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace 5"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace 6"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace 7"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace 8"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace 9"]
    bindings: ["alt+9"]

  # Monitor: =====================================================================================
  - commands: ["move-workspace --direction left"]
    bindings: ["alt+control+a"]
  - commands: ["move-workspace --direction right"]
    bindings: ["alt+control+f"]
  - commands: ["move-workspace --direction up"]
    bindings: ["alt+control+d"]
  - commands: ["move-workspace --direction down"]
    bindings: ["alt+control+s"]

  # Move: ========================================================================================
  - commands: ["move --workspace 1", "focus --workspace 1"]
    bindings: ["alt+shift+1"]
  - commands: ["move --workspace 2", "focus --workspace 2"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace 3", "focus --workspace 3"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace 4", "focus --workspace 4"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace 5", "focus --workspace 5"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace 6", "focus --workspace 6"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace 7", "focus --workspace 7"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace 8", "focus --workspace 8"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace 9", "focus --workspace 9"]
    bindings: ["alt+shift+9"]
