# =============================================================================== #
# Clean ~:                                                                        #
# =============================================================================== #
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export INPUTRC="$HOME/.bash/inputrc"
export MYVIMRC="$HOME/.config/nvim/init.lua"
export WGETRC="$HOME/.others/wgetrc"
export GIT_CONFIG_GLOBAL="$HOME/.others/gitconfig"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$HOME/.bash/history"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export IPYTHONDIR="$HOME/.cache/ipython_config"
export JUPYTER_CONFIG_DIR="$HOME/.cache/jupyter_config"
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/rc"
export XDEB_PKGROOT=${HOME}/.config/xdeb

# =============================================================================== #
# Os:                                                                             #
# =============================================================================== #
export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=5000
export PROMPT_COMMAND='history -a'
export LIBVA_DRIVER_NAME="iHD"
export LANG="en_US.UTF-8"
export LC_ALL="C.UTF-8"
export CC="gcc"

# =============================================================================== #
# Apps:                                                                           #
# =============================================================================== #
export PAGER="less"
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"

# =============================================================================== #
# Gui:                                                                            #
# =============================================================================== #
export GTK_THEME=Thorn-dark-sea
export XCURSOR_THEME=BreezeX-Black
export XCURSOR_SIZE=30

# =============================================================================== #
# Options:                                                                        #
# =============================================================================== #
set -o vi
shopt -s cdable_vars
shopt -s autocd
shopt -s cdspell
shopt -s dirspell
shopt -s dotglob
shopt -s extglob
shopt -s no_empty_cmd_completion
shopt -s nocaseglob
shopt -s histappend

# =============================================================================== #
# Completions:                                                                    #
# =============================================================================== #
bind 'TAB:menu-complete'
bind '"\e[Z": menu-complete-backward'
bind 'set show-all-if-ambiguous off'
bind 'set menu-complete-display-prefix on'
bind 'set match-hidden-files off'
bind 'set completion-ignore-case on'

# =============================================================================== #
# Prompt:                                                                         #
# =============================================================================== #
export PS1='\[\e[38;5;43;1;2m\]\w\[\e[0m\] \[\e[38;5;72;1m\]λ\[\e[0m\] '

# =============================================================================== #
# Paths:                                                                          #
# =============================================================================== #
NPM_PACKAGES="${HOME}/.local/share/npm-packages"
export PATH="$HOME/.config/bin:$HOME/.cargo/bin:$HOME/.local/bin:$NPM_PACKAGES/bin:$PATH"
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"

# =============================================================================== #
# Extrnal:                                                                        #
# =============================================================================== #
source <(carapace _carapace)
eval "$(zoxide init bash)"

# =============================================================================== #
# Fzf:                                                                            #
# =============================================================================== #
eval "$(fzf --bash)"
export FZF_DEFAULT_COMMAND="fd --hidden --strip-cwd-prefix --exclude .git"
export FZF_ALT_C_COMMAND="fd --type=d --no-hidden --strip-cwd-prefix --exclude .git"
export FZF_DEFAULT_OPTS="
    --prompt='󱓇  ' --layout=reverse
    --preview-window=right,30%
    --style=minimal --height=100% --border --preview-window right,40%
    --color fg:#DBD2C7,bg:#172526
    --color bg+:#233935,fg+:#DBD2C7
    --color hl:#88B497,hl+:#88B497,gutter:#172526
    --color pointer:#9EC59B,info:#233935
    --color prompt:#88B497,
    --color border:#233935
    --bind 'tab:accept'
"

# =============================================================================== #
# Aliases:                                                                        #
# =============================================================================== #
# =============================================================================== #
# Reset:                                                                          #
# =============================================================================== #
alias cls="tput -x clear"
alias clear="tput -x clear"
alias reset="clear"

# =============================================================================== #
# Fetch:                                                                          #
# =============================================================================== #
alias fetch="fastfetch"
alias neofetch="fastfetch"

# =============================================================================== #
# Zoxide:                                                                         #
# =============================================================================== #
alias cd="z"
alias cdf="zi"

# =============================================================================== #
# Configs:                                                                        #
# =============================================================================== #
alias dots="cd ~/.local/way.dots/"
alias bashc="nvim ~/.local/way.dots/void-dotfiles/home/.bash/bashrc"
alias wmc="nvim ~/.local/way.dots/void-dotfiles/cfg/niri/config.kdl"

# =============================================================================== #
# Services:                                                                       #
# =============================================================================== #
alias svenable="doas ln -sfv /etc/sv/$1 /var/service/"
alias svdisable="doas rm /var/service/$1"
alias svstatus="doas sv status /var/service/*"

# =============================================================================== #
# Eza:                                                                            #
# =============================================================================== #
alias ls="eza --long --group --icons=auto --git --sort=name --group-directories-first"
alias ll="eza --long --group --icons=auto --git --sort=name --group-directories-first"
alias lt="eza --long --group --icons=auto --git --only-dirs --tree --level=3 --sort=modified"

# =============================================================================== #
# Bat:                                                                            #
# =============================================================================== #
alias b="bat"
alias bn="bat --number"
alias bp="bat --plain "
alias bl="bat --line-range"
alias bpl="bat --plain --line-range"
alias bnl="bat --number --line-range"

# =============================================================================== #
# Editor:                                                                         #
# =============================================================================== #
alias v="nvim"
alias n="nvim"
alias vi="nvim"
alias nv="nvim"
alias vn="nvim"
alias vn="nvim"
alias vm="nvim"
alias vg="nohup neovide 2>/dev/null 1>&2 &"
alias ng="nohup neovide 2>/dev/null 1>&2 &"

# =============================================================================== #
# Git:                                                                            #
# =============================================================================== #
alias g="git"
alias lg="lazygit"
alias gi="g init"
alias ge="g clone"
alias gd="g diff"
alias gf="g fetch"
alias gg="g pull"
alias gb="g branch"
alias gg="g switch"
alias ga="g add --all"
alias gs="g status -s"
alias gc="g commit -m"
alias gp="g push -uf origin main"
alias gl="g log --oneline --graph --all -10"

# =============================================================================== #
# Packages:                                                                       #
# =============================================================================== #
alias pu="doas xbps-install -Syu xbps && doas xbps-install -Su"
alias pi="doas xbps-install -S"
alias pr="doas xbps-remove -Rcon"
alias pq="xbps-query -Rs"
alias pl="xbps-query -l"
alias pc="doas xbps-remove -Oo"
alias pclean="doas rm -rf /var/cache/xbps/*"

# =============================================================================== #
# Others:                                                                         #
# =============================================================================== #
alias yt-concats="yt-dlp --ignore-config --config-locations ~/.config/yt-dlp/playlist"
alias yt-music="yt-dlp --ignore-config --config-locations ~/.config/yt-dlp/music"
alias dev="browser-sync start --no-notify --server --files '**/*.html, **/*.css, **/*.js'"
alias rm="trash-put"
alias man="tldr"
alias cat="bat"
