# =============================================================================== #
# Theme:                                                                          #
# =============================================================================== #
[mgr]
marker_copied = { fg = "#172526", bg = "#88B497" }
marker_cut = { fg = "#D2696C", bg = "#F9ADA0" }
marker_marked = { fg = "#91C4C0", bg = "#87CBB1" }
marker_selected = { fg = "#568270", bg = "#568270" }
cwd = { fg = "#FFD7AA" }
find_keyword = { fg = "#568270", bg = "#233935" }
find_position = {}
count_copied = { fg = "#233935", bg = "#172526" }
count_cut = { fg = "#233935", bg = "#d2696c" }
count_selected = { fg = "#233935", bg = "#568270" }
border_symbol = "│"
border_style = { fg = "#233935" }

# =============================================================================== #
# Indicator:                                                                      #
# =============================================================================== #
[indicator]
current = { fg = "#233935", bg = "#91C4C0", reversed = true }
preview = { fg = "#88B497", bg = "#233935", underline = false }
parent  = { reversed = true }
padding = { open = "▐", close = "▌" }

# =============================================================================== #
# Tabs:                                                                           #
# =============================================================================== #
[tabs]
active = { fg = "#233935", bg = "#88B497" }
inactive = { fg = "#88B497", bg = "#172526" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# =============================================================================== #
# Mode:                                                                           #
# =============================================================================== #
[mode]
normal_main = { fg = "#233935", bg = "#91C4C0" }
normal_alt = { fg = "#91C4C0", bg = "#172526" }
select_main = { fg = "#233935", bg = "#91C4C0" }
select_alt = { fg = "#91C4C0", bg = "#172526" }
unset_main = { fg = "#233935", bg = "#FFD7AA" }
unset_alt = { fg = "#FFD7AA", bg = "#172526" }

# =============================================================================== #
# Status:                                                                         #
# =============================================================================== #
[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall = { fg = "#c8c093", bg = "#568270" }
progress_label = { fg = "#91C4C0", bold = true }
progress_normal = { fg = "#172526", bg = "#233935" }
progress_error = { fg = "#172526", bg = "#233935" }
perm_type = { fg = "#172526" }
perm_read = { fg = "#FFD7AA" }
perm_write = { fg = "#F9ADA0" }
perm_exec = { fg = "#91C4C0" }
perm_sep = { fg = "#91C4C0" }

# =============================================================================== #
# Select:                                                                         #
# =============================================================================== #
[select]
border   = { fg = "#D2696C" }
active   = { fg = "#a292a3", bold = true }
inactive = {}

# =============================================================================== #
# Pick:                                                                           #
# =============================================================================== #
[pick]
border = { fg = "#87CBB1" }
active = { fg = "#91C4C0", bold = true }
inactive = {}

# =============================================================================== #
# Input:                                                                          #
# =============================================================================== #
[input]
border = { fg = "#87CBB1" }
title = {}
value = {}
selected = { reversed = true }

# =============================================================================== #
# Completion:                                                                     #
# =============================================================================== #
[completion]
border = { fg = "#87CBB1" }
active = { reversed = true }
inactive = {}
icon_file    = ""
icon_folder  = ""
icon_command = ""

# =============================================================================== #
# Tasks:                                                                          #
# =============================================================================== #
[tasks]
border = { fg = "#87CBB1" }
title = {}
hovered = { fg = "#91C4C0" }

# =============================================================================== #
# Which:                                                                          #
# =============================================================================== #
[which]
cols = 3
mask = { bg = "#233935" }
rest = { fg = "#A1A790" }
cand = { fg = "#91C4C0" }
desc = { fg = "#87CBB1" }
separator = "  "
separator_style = { fg = "#a6a69c" }

# =============================================================================== #
# Help:                                                                           #
# =============================================================================== #
[help]
on = { fg = "#91C4C0" }
run = { fg = "#87CBB1" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#233935", bg = "#A1A790"}

# =============================================================================== #
# Notify:                                                                         #
# =============================================================================== #
[notify]
title_info = { fg = "#172526" }
title_warn = { fg = "#FFD7AA" }
title_error = { fg = "#F9ADA0" }
icon_info  = ""
icon_warn  = ""
icon_error = ""

# =============================================================================== #
# Filetype:                                                                       #
# =============================================================================== #
[filetype]
rules = [
    # images
    { mime = "image/*", fg = "#87CBB1" },

    # media
    { mime = "{audio,video}/*", fg = "#88B497" },

    # archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#D2696C" },

    # documents
    { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#6a9589" },

    # broken links
    { url = "*", is = "orphan", fg = "#D2696C" },

    # executables
    { url = "*", is = "exec", fg = "#88B497" },

    # fallback
    { url = "*", fg = "#91C4C0" },
    { url = "*/", fg = "#91C4C0" },
]
