# =============================================================================== #
# General:                                                                        #
# =============================================================================== #
gui:
  scrollHeight: 2
  mainPanelSplitMode: "flexible"
  enlargedSideViewLocation: "top"
  statusPanelView: allBranchesLog
  useHunkModeInStagingView: true
  language: "en"
  nerdFontsVersion: 3
  theme:
    activeBorderColor:
      - "#88B497"
      - bold
    inactiveBorderColor:
      - "#233935"
    searchingActiveBorderColor:
      - "#FFD7AA"
      - bold
    optionsTextColor:
      - "#91C4C0"
    selectedLineBgColor:
      - "#233935"
    selectedRangeBgColor:
      - "#88B497"
    cherryPickedCommitBgColor:
      - "#FFD7AA"
    cherryPickedCommitFgColor:
      - "#88B497"
    markedBaseCommitBgColor:
      - "#26403E"
    markedBaseCommitFgColor:
      - "#F2A597"
    unstagedChangesColor:
      - "#D2696C"
    defaultFgColor:
      - "#DBD2C7"
  authorColors:
    "*": "#87CBB1"
  commitLength:
    show: true

# =============================================================================== #
# OS:                                                                             #
# =============================================================================== #
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim --remote-wait +{{line}} {{filename}}"
  editInTerminal: true

# =============================================================================== #
# Git:                                                                            #
# =============================================================================== #
git:
  diffRenderers:
    - colorArg: "always"
      command: "delta --dark --paging=never"
  commit:
    signoff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  allBranchesLogCmds:
    - git log --color=always --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative

# =============================================================================== #
# Keybidngs:                                                                      #
# =============================================================================== #
keybinding:
  universal:
    quit: "q"
