# =============================================================================== #
# General:                                                                        #
# =============================================================================== #
gui:
  tabWidth: 2
  scrollHeight: 2
  nerdFontsVersion: 3
  showCommandLog: false
  showBottomLine: false
  expandFocusedSidePanel: false
  mouseEvents: true
  showPanelJumps: true
  useHunkModeInStagingView: true
  mainPanelSplitMode: "flexible"
  enlargedSideViewLocation: "top"
  statusPanelView: allBranchesLog
  language: auto
  timeFormat: "02 Jan 06 15:04"
  shortTimeFormat: "3:04 PM"
  theme:
    activeBorderColor:
      - "#88B497"
      - bold
    inactiveBorderColor:
      - "#233935"
    searchingActiveBorderColor:
      - "#FFD7AA"
      - bold
    optionsTextColor:
      - "#91C4C0"
    selectedLineBgColor:
      - "#233935"
    selectedRangeBgColor:
      - "#88B497"
    cherryPickedCommitBgColor:
      - "#FFD7AA"
    cherryPickedCommitFgColor:
      - "#88B497"
    markedBaseCommitBgColor:
      - "#26403E"
    markedBaseCommitFgColor:
      - "#F2A597"
    unstagedChangesColor:
      - "#D2696C"
    defaultFgColor:
      - "#DBD2C7"
  authorColors:
    "*": "#87CBB1"
  commitLength:
    show: true

# =============================================================================== #
# OS:                                                                             #
# =============================================================================== #
os:
  edit: "nvim {{filename}}"
  editAtLine: "nvim +{{line}} {{filename}}"
  editAtLineAndWait: "nvim --remote-wait +{{line}} {{filename}}"
  open: "xdg-open {{filename}} >/dev/null 2>&1 &"
  openLink: "xdg-open {{link}} >/dev/null 2>&1 &"
  editInTerminal: true
  promptToReturnFromSubprocess: true

# =============================================================================== #
# Git:                                                                            #
# =============================================================================== #
git:
  commit:
    signOff: false
  merging:
    manualCommit: false
    args: ""
  log:
    order: topo-order
    showGraph: when-maximised
    showWholeGraph: false
  allBranchesLogCmds:
    - "git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium"
  diffRenderers:
    - colorArg: always
      # useConfig: false
      command: "delta --paging=never 2>/dev/null || cat"
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  overrideGpg: false
  disableForcePushing: false

# =============================================================================== #
# Keybidngs:                                                                      #
# =============================================================================== #
keybinding:
  universal:
    quit: q
    quit-alt1: <c-c>
    return: <esc>
    quitWithoutChangingDirectory: Q
    togglePanel: <tab>
    prevItem: <up>
    nextItem: <down>
    prevItem-alt: k
    nextItem-alt: j
    prevPage: ","
    nextPage: .
    scrollLeft: H
    scrollRight: L
    gotoTop: <disabled>
    gotoBottom: ">"
    prevBlock: <left>
    nextBlock: <right>
    prevBlock-alt: h
    nextBlock-alt: l
    jumpToBlock:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
    nextMatch: "n"
    prevMatch: "N"
    startSearch: /
    optionMenu-alt1: "?"
    select: <space>
    goInto: <enter>
    openRecentRepos: <c-r>
    confirm: <enter>
    remove: d
    new: "n"
    edit: e
    openFile: o
    scrollUpMain: <up>
    scrollDownMain: <down>
    scrollUpMain-alt1: K
    scrollDownMain-alt1: J
    executeShellCommand: ":"
    createRebaseOptionsMenu: m
    pushFiles: P
    pullFiles: p
    refresh: R
    createPatchOptionsMenu: <c-p>
    nextTab: "]"
    prevTab: "["
    nextScreenMode: +
    prevScreenMode: _
    undo: z
    redo: <c-z>
    filteringMenu: <c-s>
    diffingMenu: W
    diffingMenu-alt: <c-e>
    copyToClipboard: <c-o>
    openDiffTool: <c-t>
    submitEditorText: <enter>
    extrasMenu: "@"
    toggleWhitespaceInDiffView: <c-w>
    increaseContextInDiffView: "}"
    decreaseContextInDiffView: "{"
